# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-feed
# spec:
#   selector:
#     matchLabels:
#       app: backend-feed
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: backend-feed
#     spec:
#       containers:
#       - env:
#         - name: backend-feed
#           image: docker.io/mrbraimoh/udagram-api-feed:v4
#           ports:
#           - containerPort: 80
#           resources:
#             limits:
#               cpu: 500m
#             requests:
#               cpu: 200m
#         envFrom:
#         - configMapRef:
#             name: env-config

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - env:
        - name: backend-feed
        envFrom:
        - configMapRef:
            name: env-config
            optional: true
        - secretRef:
            name: env-secret
            optional: true
        image: docker.io/mrbraimoh/udagram-api-feed:v5
        name: backend-feed
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-feed